#include "hal_data.h"

#define check_bit(data, loc)        ((data) & (0x1<<(loc)))

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    const uint8_t array[] = {
        0xFC, // 0
        0x60, // 1
        0xDA, // 2
        0xF2, // 3
        0x66, // 4
        0xB6, // 5
        0xBE, // 6
        0xE0, // 7
        0xFE, // 8
        0xF6  // 9
    };

    int index = 0;

    while(1)
    {
        R_BSP_PinAccessEnable();

        R_BSP_PinWrite(SRCLK, BSP_IO_LEVEL_HIGH);
        R_BSP_PinWrite(RCLK, BSP_IO_LEVEL_LOW);

        segment_show(array[index++]);
        set_digits(0x80);

        R_BSP_PinAccessDisable();

        if(index > 9) {
            index = 0;
        }

        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
    }
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

void segment_show(int number)
{
    for (uint8_t i = 0; i < 8; i++)
    {
        if (check_bit(number, i))
        {
            R_BSP_PinWrite(SER_SDI, BSP_IO_LEVEL_HIGH);
        }
        else
        {
            R_BSP_PinWrite(SER_SDI, BSP_IO_LEVEL_LOW);
        }

        R_BSP_PinWrite(SRCLK, BSP_IO_LEVEL_HIGH);
        R_BSP_PinWrite(SRCLK, BSP_IO_LEVEL_LOW);
    }
}

void set_digits(int digit)
{
    for (uint8_t i = 0; i < 8; i++)
    {
        R_BSP_PinWrite(SER_SDI, BSP_IO_LEVEL_LOW);

        if (check_bit(digit, i))
        {
            R_BSP_PinWrite(SER_SDI, BSP_IO_LEVEL_LOW);
        }
        else
        {
            R_BSP_PinWrite(SER_SDI, BSP_IO_LEVEL_HIGH);
        }
        R_BSP_PinWrite(SRCLK, BSP_IO_LEVEL_HIGH);
        R_BSP_PinWrite(SRCLK, BSP_IO_LEVEL_LOW);
    }

    R_BSP_PinWrite(RCLK, BSP_IO_LEVEL_HIGH);
    R_BSP_PinWrite(OE, BSP_IO_LEVEL_LOW);
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        IOPORT_CFG_OPEN (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
